# Generated by Django 5.1.6 on 2025-02-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('taxi', 'Taxi'), ('Kous', 'Kous'), ('tram', 'Tramway'), ('train', 'Train'), ('metro', 'Metro')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes for this segment')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys_ended', to='transport.station')),
                ('start_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys_started', to='transport.station')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='available_transports',
            field=models.ManyToManyField(blank=True, related_name='stations', to='transport.transport'),
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_order', models.PositiveIntegerField(help_text='The order of this segment within the journey')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers (optional)', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='transport.journey')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments_to', to='transport.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments_from', to='transport.station')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
            options={
                'ordering': ['segment_order'],
            },
        ),
    ]
